# Generated by Django 4.1 on 2022-08-10 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_post_publish_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
